name: jjwines
favicon: null
layout_spectrum: 0.5952482558786869
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#af8701'
    - '#b3a98c'
    - '#777777'
  brandStrength: 0.5
  lightness: 0.343812458217144
  saturation: 0.6639263951219618
  rhythmicContrast: 0.0005050939507782459
purpose: []
