favicon: null
name: jjwines
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0
  rhythmicContrast: 1
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#af8701'
    - '#b3a98c'
    - '#777777'
  lightness: 0.9375
typography_spectrum: 1
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
